
    device_sn: 14211019
    b_offset: -43.179478
    p_offset: 24.743038 
    b_tilt:
      - -4.510122
      - -4.538697
      - -4.502089
      - -4.502445
    b_shift:
      - 0.009683
      - -0.032965
      - 0.031151
      - -0.036911
    b_shift_1:
      - -0.037146
      - 0.01136
      - 0.004727
      - 0.025794
    h_adjustment: -0.090932
    t_distance_correction: 2.026481
    b_distance_correction: 2.002559
    b_e_dec: -0.0032719 
    b_e_dec_1: 0.00302799 
    b_e_phase: 75.3
    nominal_intensity:
      - 647.0 
      - 578.0 
    nominal_voltage: 40000 
    t_ifactor:
      - 1.0
      - 1.0 
      - 1.0 
      - 1.0 
    b_ifactor:
      - 1.0 
      - 1.0 
      - 1.0 
      - 1.0 
    t_refl_factor: 0.1450
    b_refl_factor: 0.0768
    t_alpha: 0.109075
    b_alpha: 0.102101
    t_gamma: 0.079831
    b_gamma: 0.074067
    t_vbr0: 48930
    b_vbr0: 49147
    temp_vbr0: 49
    min_bias: 28000
    v_offset: 600
    
