
    device_sn: 14216001
    b_offset: 37.012738
    p_offset: 22.545104 
    b_tilt:
      - -4.476116
      - -4.451219
      - -4.48677
      - -4.415306
    b_shift:
      - 0.059213
      - 0.103469
      - -0.053952
      - 0.041621
    b_shift_1:
      - 0.08142
      - 0.074599
      - 0.006975
      - 0.001188
    h_adjustment: -0.092
    t_distance_correction: 2.30912
    b_distance_correction: 2.306752
    b_e_dec: -0.00136678 
    b_e_dec_1: 0.00300022 
    b_e_phase: 75.3
    nominal_intensity:
      - 730.0 
      - 718.0 
    nominal_voltage: 40000 
    t_ifactor:
      - 1.0
      - 1.0 
      - 1.0 
      - 1.0 
    b_ifactor:
      - 1.0 
      - 1.0 
      - 1.0 
      - 1.0 
    t_refl_factor: 0.0945
    b_refl_factor: 0.2023
    t_vbr0: 50063
    b_vbr0: 48372
    temp_vbr0: 40
    min_bias: 28000
    v_offset: 600